Sprint 16
RdDevi1/TrackerApp pull request #3
Opened 2023-05-22 19:18 UTC by RdDevi1

2023-05-23 19:36 UTC, ABashkirova requested changes
Заметила две ошибки:

1) на маленьких экранах расписание не умещается, а скрол у таблицы заблокирован. В итоге воскресенье мне выбрать не дадут
2) при заполненных всех полях кнопка создать была не активна. Нужно попробовать позаполнять форму в разном порядке, и отследить после какого изменения не перерасчитывается доступность кнопки создания. 

<img width="487" alt="Снимок экрана 2023-05-23 в 21 50 40" src="https://github.com/RdDevi1/TrackerApp/assets/20269264/fa01d306-eec3-4747-be60-78545d1d0f3a">

https://github.com/RdDevi1/TrackerApp/assets/20269264/d8732ecb-1091-4344-a2b3-4628a8ca6b91

2023-05-23 19:36 UTC, ABashkirova commented on TrackerApp/UI/Categories/CategoriesViewController.swift
> +        viewModel = CategoriesViewModel(selectedCategory: selectedCategory)
Это этого шага здесь можно легко избавиться, передав явно вьюмодель в инициализатор
1) VC делает не свою работу - создает часть своего модуля MVVM - ViewModel
2) раскрываем для VC зависимости вьюмодели, а точнее прям Model протащили в VC. по схеме в MVVM вьюконтроллер ничего не знает про модель. Здесь это не так 

Надо исправить

И заметь, что порядок функций стоит держать такой: инициализатор, жизненный цикл, публичные методы, приватные методы

2023-05-23 19:36 UTC, ABashkirova commented on TrackerApp/UI/Categories/CategoriesViewController.swift
> +        let deleteAction = UIAlertAction(title: "Удалить", style: .destructive) {[weak self] _ in
давай договоримся, что у фигурной скобки всегда должны быть пробелы вокруг
```suggestion
        let deleteAction = UIAlertAction(title: "Удалить", style: .destructive) { [weak self] _ in
```

2023-05-23 19:36 UTC, ABashkirova commented on TrackerApp/UI/Categories/CategoriesViewModel.swift
> +    init(selectedCategory: TrackerCategory?) {
у CategoriesViewModel есть еще один слой Model – это `trackerCategoryStore`. Их обе стоит размещать в инициализатор. 

Создавать же стор можно в месте, где ты навигируешь на этот модуль (Categories).

В продакшене часто можно встретить фабрики модулей, так называемые ассамблеи (Assembly). Они решают ровно одну задачу: приготовить правильно модуль. 
Для MVVM такая фабрика бы получала/создавала Model, инициализировала ViewModel, и от ViewModel собирала бы ViewController.
Матрешкой: Model < ViewModel < ViewControoller. 
Кроме инициализации, такая фабрика выставляет связи (в твоем случае делегатов). 
Результатом работы – UIViewController (обезличенный), который можно презентовать в месте вызова.

Итого: минимально здесь нужно поправить – передать в инициализатор стор (по протоколу) и сделать сборку модуля в момент перехода.
Супер круто: переместить этот код в дополнительную сущность с фабричным методом.

2023-05-23 19:36 UTC, ABashkirova commented on TrackerApp/UI/Categories/CategoriesViewModel.swift
> +            try trackerCategoryStore.makeCategory(with: label)
метод возвращает категорию, но никуда ее не сохраняет. Xcode показывает ворнинг, который нужно устранить (гигиенические правила: не сдавай работу с ворнингами). 

Но так как ты не сохраняешь никуда результат, но при этом все равно вызываешь этот метод, намекает на то, что эта функция не только создает категорию ( а еще и сохраняет ее). То есть метод уже решает две задачи, и вторая с сохранением является сайдэффектом. Таких функций следует избегать и делить на два шага. Либо называть их соответствующе

2023-05-23 19:36 UTC, ABashkirova commented on TrackerApp/UI/Categories/CategoryCell.swift
> +final class CategoryCell: UITableViewCell {
Заметила, что не все классы помечены `final`. Надо придерживаться одного правила по всему проекту

2023-05-23 19:36 UTC, ABashkirova commented on TrackerApp/UI/Categories/CategoryCell.swift
> +            label.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -83),
обычно верстают от крайнего элемента (checkmarkImage). 

Так ты гарантируешь, что элемент справа, будет подталкивать левый, чтобы они не переселкались. Сейчас же просто какая-то константа стоит, не раскрывающая сути верстки.

2023-05-23 19:36 UTC, ABashkirova commented on TrackerApp/UI/Categories/CategoryCell.swift
> +            label.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -83),
Заметила, что у тебя таблица передает размер ячейки. Обычно хватает настройки UITableViewAutomaticDimension и хорошей верстки у элементов ячейки – тогда таблица сама хорошо определяет размеры своих ячеек. 

Попробуй разобраться, и может быть избаваиться от лишнего кода c `tableView(_ tableView:, heightForRowAt indexPath:)`

2023-05-23 19:36 UTC, ABashkirova commented on TrackerApp/UI/CreatingEvents/CreateEventViewController.swift
> +    private lazy var categoriesVC = CategoriesViewController(selectedCategory: self.trackerCategory)
Есть какой-то скрытый смысл создавать вью-контроллеры в свойствах другого вью-контроллера?

Я не рекомендую так делать, на своей практике не встречала такого подхода, кроме как без сохранения ссылки не получится. Здесь не этот случай я полагаю. В общем случае хранить ссылки на другие вью-контроллеры нам не нужно:
1) созданный и запрезенченный вью контроллер хранит сама система с помощью иерархии вью контроллеров в контейнерах (виндоу, навигейшен, таббар контроллеры)
2) сохраняя таким образом ссылку, вью контроллер будет жить пока живет этот экран. То есть тебе нужно перед повторным открытием этих контроллеров убедиться в правильности их состояния. А если они тебе больше не понадобятся - они будут жить больше, чем на самом деле необходимо. 

Поэтому этот код надо переписать, и создавать контроллеры только в момент перехода.

2023-05-23 20:54 UTC, RdDevi1 commented on TrackerApp/DataStore/TrackerCategoryStore.swift
>  import UIKit
единственное место где нужен UIkit там 
`convenience override init() {
        let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
        try! self.init(context: context)
    }`
    но это прям по учебнику и в авторском решении по теме контекста аналогично импортирован UIKit ¯_(ツ)_/¯

2023-05-24 07:06 UTC, ABashkirova commented on TrackerApp/DataStore/TrackerCategoryStore.swift
>  import UIKit
> но это прям по учебнику и в авторском решении по теме контекста аналогично импортирован UIKit 

🤯 точно, совсем забыла, этот момент авторы уже правят. В любом случае пример дан для простоты старта, в своих приложениях так делать не рекомендуется

В любом случае, в проде никто не создает контейнер в AppDelegate. На самом деле ничего страшного не произойдет, если ты его поместишь в отдельный класс-обертку, и например через shared отдашь своим дата-сторам. 

Так и от UIKit избавимся, и архитектуру соблюдем

2023-05-24 08:29 UTC, RdDevi1 commented on TrackerApp/UI/CreatingEvents/CreateEventViewController.swift
> +    private lazy var categoriesVC = CategoriesViewController(selectedCategory: self.trackerCategory)
тут я пробовал сделать передачу расписания и выбранной категории на экран создания трекера через замыкание, и по аналогии с примером передачи данных через вью контроллеры сделал так, и указал lazy чтобы контроллер создался только в момент перехода на него из таблицы

2023-05-24 08:38 UTC, ABashkirova commented on TrackerApp/UI/CreatingEvents/CreateEventViewController.swift
> +    private lazy var categoriesVC = CategoriesViewController(selectedCategory: self.trackerCategory)
> и указал lazy чтобы контроллер создался только в момент перехода на него из таблицы

для первого раза лейзи сработает как ты описываешь. Но когда ты уйдешь с этих экранов (смахнешь), они все еще будут в памяти. И. при повторном переходе вызовутся те же самые контроллеры. 

Меня больше смущает то что они живут больше чем положено, и то что их сохраненный стейт (с предыдущего запуска) никак не будет сброшен, это нужно руками гарантировать.

2023-05-24 08:46 UTC, RdDevi1 commented on TrackerApp/UI/CreatingEvents/CreateEventViewController.swift
> +    private lazy var categoriesVC = CategoriesViewController(selectedCategory: self.trackerCategory)
наверное, я тогда не совсем понимаю логику)) к примеру открыли выбор расписания, выбрали 3 дня каких то, нажали готово (экран выбора расписания ушел), в таблице создания трекера стали видны видны эти 3 дня. Потом передумали и решили добавить еще 1 день, снова открываем экран выбора расписания и там уже эти 3 дня отмечены и мы добавляем четвертый день. Возможно ошибаюсь, но пока не понял почему контроллеры выбора расписания и выбора категории не должны жить пока создается трекер...

2023-05-25 13:53 UTC, ABashkirova commented on TrackerApp/UI/CreatingEvents/CreateEventViewController.swift
> +    private lazy var categoriesVC = CategoriesViewController(selectedCategory: self.trackerCategory)
То как ты говоришь – работает в этой конкретной задаче. Но это очень связный код, который не масштабируется под другие задачи и в этом его минус.

Я готова принять как есть, только лишь сделав поблажку что проект маленький и тут это будет работать и никогда не будет масштабироваться 👍🏻. Но еще раз попробую донести как стоит рассуждать. 

Каждый отдельный экран – это самостоятельный модуль, он не должен знать в каком контексте/экране он будет запущен. Его ответственность запустится, отработать для пользователя, вернуть результат. 
То с какими данными он запустится (изначально сохраненное расписание) – это ответственность модуля, который запустит модуль расписания. Он должен эти данные сохранять и передавать их по требованию открыть "экран расписания". И этот же модуль создания трекера должен получать результаты работы модуля с расписанием, когда тот закончил работу. 
Помнить что пользователь уже работал с этим или с другим экраном через сохранение ссылок на экраны – не рабочая схема)

Когда мы отделяем модули друг от друга – мы получаем гибкость нашей системы: один и тот же экран сможет запускаться из разных условий. Например, ты сможешь добавить быстрое действие для готовой заметки – "Изменить расписание" и открывать только этот экран с расписание, не в контексте создания нового трекера.  И он будет отлично работать, если изначально не зависит от других экранов.

Кроме гибкости, у тебя архитектурно настроены все взаимотношения верно и ничего не делается лишний раз. 

Да и экраны не живут дольше положенного и не создаются, если не нужны.Еще раз: контроллеры хранить в своих переменных скорее всего большая ошибка и потенциальные утечки памяти. За тебя система уже прекрасно их умеет хранить, тебе это не нужно делать руками. 
Этот наброс не очень существенен в этой задаче: экраны то простые, где там памяти течь. Но так будет работать до тех пор, пока ты не столкнешься с продакшен задачей, где экран потребляет ресурсы файловой системы, камеры, сетевые взаимодействия, видео-потоки. 

И именно поэтому архитектуры важны, если ты правильно их готовишь, то у тебя просто естественным образом получится не совершить таких ошибок.

2023-05-25 13:56 UTC, RdDevi1 commented on TrackerApp/UI/Onboarding/OnboardingViewController.swift
> +    }()
выглядит и круто и немного как оверинжиниринг пока для меня)) было интересно поизучать и попробовать)

2023-05-25 14:17 UTC, RdDevi1 commented on TrackerApp/UI/CreatingEvents/CreateEventViewController.swift
> +    private lazy var categoriesVC = CategoriesViewController(selectedCategory: self.trackerCategory)
Спасибо за подробное разъяснение) в целом я понимаю, что хранение контроллеров в переменных это плохая практика и создает сильную зависимость от конкретного класса. Как например во вью модели стоило точно поменять trackerCategoryStore на протокол так как может меняться БД. Но, возможно, из-за того, что пока не сталкивался с масштабируемостью, большими экранами и другими сложными моментами - показалось что тут как раз как ты написала - это будет не очень существенно с учетом простоты экранов и контент на них без сети и чего-то тяжелого. Для привыкания к хорошей практике буду стараться избегать таких моментов в том числе для простых экранов

2023-05-25 18:11 UTC, IBDesignable commented on TrackerApp/UI/CreatingEvents/CreateEventViewController.swift
> +    private lazy var categoriesVC = CategoriesViewController(selectedCategory: self.trackerCategory)
Не все сразу, не надо переживать что в учебном проекте сделал что-то не так, это как раз та самая площадка где и нужно набивать шишки) чем больше тем лучше)

2023-05-25 18:14 UTC, ABashkirova approved these changes

2023-05-25 18:14 UTC, ABashkirova commented on TrackerApp/UI/EnterViewController.swift
> +            userDefaults.set(true, forKey: Keys.onboardingShown.rawValue)
хорошо!

2023-05-25 18:14 UTC, ABashkirova commented on TrackerApp/UI/Onboarding/OnboardingViewController.swift
> +        pageControl.numberOfPages = Pages.allCases.count
супер!

2023-05-25 18:14 UTC, ABashkirova commented on TrackerApp/UI/Onboarding/OnboardingViewController.swift
> +        return vc
можно сразу вернуть, если ссылка не нужна. 
```suggestion
        return OnboardingPageViewController(page: pages[index])
```

2023-05-26 08:11 UTC, merged